/*
    UIPromptMachineSessionList.cpp
    

*/
//UIPromptMachineSessionList.cpp generated by cbtek on 11-24-2016 at 01:51:42 AM

#include "UIPromptMachineSessionList.h"
#include "ui_UIPromptMachineSessionList.h"

namespace cbtek {
namespace products {
namespace productivity {
namespace prompt_machine {


UIPromptMachineSessionList::UIPromptMachineSessionList(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UIPromptMachineSessionList)
{
    m_ui->setupUi(this);
}





UIPromptMachineSessionList::~UIPromptMachineSessionList()
{
    delete m_ui;
}

}}}}//end namespace

